language: java
jdk:
- openjdk8
- openjdk15
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- travis_wait ./gradlew check uberJar
before_deploy:
- git config --local user.name "Jason Walonoski"
- git config --local user.email "jwalonoski@mitre.org"
- export TRAVIS_TAG=master-branch-latest
- git tag -d $TRAVIS_TAG
- git remote add upstream "https://$GH_TOKEN@github.com/synthetichealth/synthea.git"
- git push upstream :$TRAVIS_TAG
- git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file: build/libs/synthea-with-dependencies.jar
  skip_cleanup: true
  on:
    tags: false
    jdk: openjdk8
  overwrite: true
  prerelease: true
after_success:
- bash <(curl -s https://codecov.io/bash)
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  deploy.sh
notifications:
  slack:
    secure: dtqmeVNcKx8KVaSHTevQ0Osx/e+bYBL/xezlotobyMXBfNMxtDewrXA3dhkoj8vhXoyWvf7or+QY9PikTKYeaI+/WMJ+Mc8DbFILDxH3m1/968wE7MjIam2pmwzIzEiWxG6i6qoMc2/2PZJTT1XRRzEKqDBmMtij39aGnF7G/JitlMalNppEzPK0VHc1S/eP6XMjeFcUlp0etyPpe6xmv1Of+SuCaTcFbfEae9moYg9VgHmNr+xzlc3QT7Z6YUvvrWGmzgcQGjJdWeoZRHSHLbs+brjm6+zwtH+su8t4GIDQPL0sz8D8Uu4y5N0ff7aQ9/ezI8sAW2nfVSQl77V12ZqSvWgqAZ3yxUIrg6LsCDYPq4PJ1X/PvM1wgDTqoFoTdQ2m2KEe7vJ+leASDElWUR1QL4X2lK0aXgXNGxYmks2MoU69zrzd9dgCeJrveLZGA8YOB62CKSfy/viVhM4KntaatYkufD0GgWumni3wFLrW9mGTHi073PMEcx0fpsc+QyZJmbAgS9je6UCPf5fpOLc0K6SIFBtDbYiXSaBotG3rbdy8M83LQC4N3sPfk/cvn7mdptrWsha4laVXwA87ogOLKjnEFCV/3RfYj9apBWZ6WcfEdnN10QProCq7emJW+lUbexSe1xz5ZPmk8TMMND3BOVbbF1t7XKdWb/QuPc8=
